#
# NOTE: This stack is part of a multi-file Docker Compose setup.
#
# Other Compose files in this workspace:
#   - docker-compose.ai.yml: AI/ML services (Frigate, Ollama, Stable Diffusion WebUI, Whisper, Qdrant, TGI, XTTS, TTS)
#   - docker-compose.utils.yml: Utility/infrastructure services (Portainer, Watchtower, Nginx Proxy Manager, Tailscale, Cloudflared)
#
# This file (docker-compose.home.yml) contains core home automation services, e.g.:
#   - homeassistant
#   - zigbee2mqtt
#   - (and others, see file for details)
#
# See the other files for additional services and to bring up the full stack, use:
#   docker-compose -f "docker-compose.ai.yml" -f "docker-compose.home.yml" -f "docker-compose.utils.yml" up -d
#
# All configuration, healthcheck, and environment variable practices in this file must comply with [AI_CODING_BASELINE_RULES.md](./AI_CODING_BASELINE_RULES.md). See that guide for required standards on configuration, healthchecks, logging, commit practices, and more.
#

version: '3.8'
# env_file moved into each service (env_file not allowed at top-level)
# env_file:
#   - .env
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2025.5.0  # pinned version
    # runs as root due to host networking and privileged mode; documented exception per EXC-01
    container_name: homeassistant
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - ./homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Australia/Brisbane
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8123/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Zigbee2MQTT (Commented out until dongle is available)
  # zigbee2mqtt:
  #   image: koenkk/zigbee2mqtt:latest
  #   container_name: zigbee2mqtt
  #   restart: unless-stopped
  #   volumes:
  #     - ./zigbee2mqtt/data:/app/data
  #     - /run/udev:/run/udev:ro
  #   ports:
  #     - '8081:8081' # Zigbee2MQTT frontend
  #   environment:
  #     - TZ=Australia/Brisbane
  #   devices:
  #     - /dev/ttyUSB0:/dev/ttyUSB0 # Make sure this matches your dongle path

# Add more smart home services as needed

