#
# NOTE: This stack is part of a multi-file Docker Compose setup.
#
# Other Compose files in this workspace:
#   - docker-compose.ai.yml: AI/ML services (Frigate, Ollama, Stable Diffusion WebUI, Whisper, Qdrant, TGI, XTTS, TTS)
#   - docker-compose.utils.yml: Utility/infrastructure services (Portainer, Watchtower, Nginx Proxy Manager, Tailscale, Cloudflared)
#
# This file (docker-compose.home.yml) contains core home automation services, e.g.:
#   - homeassistant
#   - zigbee2mqtt
#   - (and others, see file for details)
#
# See the other files for additional services and to bring up the full stack, use:
#   docker-compose -f "docker-compose.ai.yml" -f "docker-compose.home.yml" -f "docker-compose.utils.yml" up -d
#

version: '3.8'
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - ./homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Australia/Brisbane

  # Zigbee2MQTT (Commented out until dongle is available)
  # zigbee2mqtt:
  #   image: koenkk/zigbee2mqtt:latest
  #   container_name: zigbee2mqtt
  #   restart: unless-stopped
  #   volumes:
  #     - ./zigbee2mqtt/data:/app/data
  #     - /run/udev:/run/udev:ro
  #   ports:
  #     - '8081:8081' # Zigbee2MQTT frontend
  #   environment:
  #     - TZ=Australia/Brisbane
  #   devices:
  #     - /dev/ttyUSB0:/dev/ttyUSB0 # Make sure this matches your dongle path

# Add more smart home services as needed

